import { Gilda_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/footer/footer";
import ReduxProvider from "@/context/ReduxProvider";
import ToasterContext from "@/context/ToasterContext";
import { BookingProvider } from "@/context/BookingContext";

const gilda = Gilda_Display({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={gilda.className}>
        <ReduxProvider>
          <ToasterContext />
          <BookingProvider>
            <Header />
            <div className="root">{children}</div>
            <Footer />
          </BookingProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
